[package]
name = "bashlens-rules"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
regex = "1.10"
anyhow = "1.0"
bashlens-parser = { path = "../parser" }
tree-sitter = "0.26"
streaming-iterator = "0.1"
include_dir = "0.7"
